@host = https://localhost:5001

### Analyse an identity document supplied as a public URL
POST {{host}}/api/ImageAnalysis/imageAnalyse
Content-Type: multipart/form-data; boundary=----RequestBoundary

------RequestBoundary
Content-Disposition: form-data; name="type"

idpassport
------RequestBoundary
Content-Disposition: form-data; name="paths"

https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png
------RequestBoundary
Content-Disposition: form-data; name="gps"

40.712776,-74.005974
------RequestBoundary
Content-Disposition: form-data; name="clientIP"

8.8.8.8
------RequestBoundary
Content-Disposition: form-data; name="clientCamera"

false
------RequestBoundary--

### Analyse an uploaded file
# Replace ./sample-passport.jpg with a local image before sending.
POST {{host}}/api/ImageAnalysis/imageAnalyse
Content-Type: multipart/form-data; boundary=----RequestBoundary

------RequestBoundary
Content-Disposition: form-data; name="type"

idpassport
------RequestBoundary
Content-Disposition: form-data; name="images"; filename="sample-passport.jpg"
Content-Type: image/jpeg

< ./sample-passport.jpg
------RequestBoundary--

### Detect face attributes in a selfie
POST {{host}}/api/ImageAnalysis/imageAnalyse
Content-Type: multipart/form-data; boundary=----RequestBoundary

------RequestBoundary
Content-Disposition: form-data; name="type"

face
------RequestBoundary
Content-Disposition: form-data; name="images"; filename="selfie.jpg"
Content-Type: image/jpeg

< ./selfie.jpg
------RequestBoundary--

### Error case: neither images nor paths supplied -> 400
POST {{host}}/api/ImageAnalysis/imageAnalyse
Content-Type: multipart/form-data; boundary=----RequestBoundary

------RequestBoundary
Content-Disposition: form-data; name="type"

invoice
------RequestBoundary--
